### ISSUE TITLE
How to boot an image with Qemu?

### ISSUE THREAD

**Issue by onlyjob** [ant9000/acmesystems-image-builder#1]
Would it be possible to document how to boot a Debos-generated image with Qemu?

Thanks.

**Comment by ant9000** [comment]
I've never used qemu for that, sorry.
Just a quick search:
`   https://translatedcode.wordpress.com/2016/11/03/installing-debian-on-qemus-32-bit-arm-virt-board/`
You should be able to arrange the storage with something like
`   -drive if=none,file=debian-stretch-roadrunner.img,format=raw,id=hd`
The dtb could be appended to the kernel zImage you pass to -kernel, and there is no initrd here.

Why would you do that, though? I bet it's gonna be extremely slow and won't behave in any case like real hardware.

A pretty standard trick, useful for simple stuff, is to copy `/usr/bin/qemu-arm-static` from the host into `/usr/bin` inside the debootstrap dirs, and then you can happily `chroot` into it.

Antonio

**Comment by onlyjob** [comment]
Emulated hardware can be useful for CI as well as for troubleshooting bugs.
Slow is better than nothing, when you do not have the hardware... :)
